### ISSUE TITLE
:Denite coc-workspace doens't work while :CocList -I symbols does

### ISSUE THREAD

**Issue by kantord** [neoclide/coc-denite#9]
If I do `:Denite coc-workspace` in a file, I get this error:

![2020-11-25T19:08+01:00](https://user-images.githubusercontent.com/3704904/100266162-a6123680-2f51-11eb-9703-e5e9a6589f01.png)

Getting the same error in different file types:

![2020-11-25T19:09+01:00](https://user-images.githubusercontent.com/3704904/100266213-bb876080-2f51-11eb-9d2b-25a7b709a14f.png)

and even in different projects.

However, `:Denite coc-symbols` works fine everywhere, and I can even do `:CocList -I symbols` to successfully search workspace symbols in all of the mentioned places

Log output:

```
2020-11-25T19:09:09.298 ERROR (pid:1937029) [attach] - Request error: workspaceSymbols [] Error: Action "workspaceSymbols" not exists
    at Plugin.cocAction (/home/kdani/repos/perfect-arch-config/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:24037:19)
    at NeovimClient.<anonymous> (/home/kdani/repos/perfect-arch-config/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:11619:40)
    at NeovimClient.emit (events.js:223:5)
    at NeovimClient.handleRequest (/home/kdani/repos/perfect-arch-config/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:11836:14)
    at NvimTransport.emit (events.js:223:5)
    at NvimTransport.parseMessage (/home/kdani/repos/perfect-arch-config/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:12071:18)
    at DecodeStream.<anonymous> (/home/kdani/repos/perfect-arch-config/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:12056:18)
    at DecodeStream.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at DecodeStream.Readable.push (_stream_readable.js:224:10)
    at DecodeStream.Transform.push (_stream_transform.js:150:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/kdani/repos/perfect-arch-config/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:15028:12)
    at DecodeBuffer.flush (/home/kdani/repos/perfect-arch-config/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:14018:12)
    at DecodeStream._transform (/home/kdani/repos/perfect-arch-config/dotfiles/vim/.vim/plugged/coc.nvim/build/index.js:15034:16)
    at DecodeStream.Transform._read (_stream_transform.js:189:10)

```

**Comment by chemzqm** [comment]
No such support

**Comment by kantord** [comment]
I don't understand :thinking: If this is not what `coc-workspace` is for, then the what *is* it for? :thinking:
